# EKF Parameters
frequency: 50  # Filter update frequency in Hz
sensor_timeout: 0.1  # Max time in seconds to wait for sensor messages
two_d_mode: true  # Enforce 2D mode, ignoring roll and pitch

# Frame IDs
world_frame: odom  # World frame ID
base_link_frame: base_link  # Robot base frame ID
odom_frame: odom  # Odometry frame ID

# Process Noise Covariance

# Odometry Sensor Configuration
odom0: /odom
odom0_config: [true, true, false,  # x, y, z
               false, false, true, # roll, pitch, yaw
               true, true, false,  # vx, vy, vz
               false, false, true] # vroll, vpitch, vyaw

odom0_differential: false




# IMU Sensor Configuration
imu0: /limo/imu
imu0_config: [false, false, false, # x, y, z
              true,  true,  true,  # roll, pitch, yaw
              false, false, false, # vx, vy, vz
              true,  true,  true]  # vroll, vpitch, vyaw

imu0_differential: true



# Control Settings
use_control: false

# Debugging and Output
publish_tf: false
publish_acceleration: false


